# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DP5G36d6xw9tslsbLDAUdh3zveM9mzi4
"""

import pandas as pd 
import numpy  as np 

df = pd.read_csv('archive (1).zip',header=None)

df.columns=['y','x']

df

df.info()

df.describe()

df.drop_duplicates(subset=['x'], keep='first', inplace=True, ignore_index=True)

df['len'] = df['x'].str.len()

df.sort_values('len',ascending=True)

df.dropna(inplace=True)

df.len.hist()